# command: podman build --build-arg USE_LOCAL_DEEPEP=true --volume /opt/cray/libfabric/1.22.0:/mnt/libfabric:ro -f $HOME/developer/DeepEP/dockers/Dockerfile.deepep -t deepep .


# =========================
# Use the pytorch image which has CUDA 12.9 inside.
# =========================
FROM nvcr.io/nvidia/pytorch:25.06-py3 AS base

ENV SHELL=/bin/bash
ENV PIP_NO_CACHE_DIR=1


# copy libfabric library from system to container and create lib symlink
RUN mkdir -p /opt/cray/libfabric/1.22.0 && \
    cp -a /mnt/libfabric/* /opt/cray/libfabric/1.22.0/ && \
    cd /opt/cray/libfabric/1.22.0 && ln -s lib64 lib

ENV LIBFABRIC_HOME=/opt/cray/libfabric/1.22.0


# =========================
# Install Python packages
# =========================
RUN unset PIP_CONSTRAINT && pip install debugpy dm-tree torch_tb_profiler einops wandb

# =========================
# Install DeepEp and NVSHMEM
# =========================

# Includes version 2.4.1
ENV GDRCOPY_HOME=/usr/lib/aarch64-linux-gnu 

ENV CUDA_HOME=/usr/local/cuda
# Set MPI environment variables. Having errors when not set.
ENV CPATH=/usr/local/mpi/include:$CPATH
ENV LD_LIBRARY_PATH=/usr/local/mpi/lib:$LD_LIBRARY_PATH
ENV LD_LIBRARY_PATH=/usr/local/aarch64-linux-gnu:$LD_LIBRARY_PATH


# **NOTE: After NVSHMEM v3.3.9, it is no longer necessary to apply our patch to achieve optimal performance.**

# =========================
# Build NVSHMEM with DeepEP patches
# =========================

WORKDIR /home/dpsk_a2a
RUN wget https://github.com/NVIDIA/nvshmem/archive/refs/tags/v3.4.5-0.tar.gz \
        -O nvshmem-3.4.5-0.tar.gz && \
    tar -xzf nvshmem-3.4.5-0.tar.gz && \
    mv nvshmem-3.4.5-0 deepep-nvshmem && \
    rm nvshmem-3.4.5-0.tar.gz

RUN ln -s /usr/lib/aarch64-linux-gnu/libmlx5.so.1 /usr/lib/aarch64-linux-gnu/libmlx5.so

# To build DeepEP the IBGDA option has to be activated
WORKDIR /home/dpsk_a2a/deepep-nvshmem
RUN NVSHMEM_SHMEM_SUPPORT=0 \
    NVSHMEM_UCX_SUPPORT=0 \
    NVSHMEM_USE_NCCL=0 \
    NVSHMEM_MPI_SUPPORT=0 \
    NVSHMEM_IBGDA_SUPPORT=1 \
    NVSHMEM_PMIX_SUPPORT=0 \
    NVSHMEM_TIMEOUT_DEVICE_POLLING=0 \
    NVSHMEM_USE_GDRCOPY=1 \
    NVSHMEM_LIBFABRIC_SUPPORT=1 \
    cmake -S . -B build/ -DCMAKE_INSTALL_PREFIX=/home/dpsk_a2a/deepep-nvshmem/install -DCMAKE_CUDA_ARCHITECTURES=90 && cd build && make install -j

# =========================
# Get DeepEP source code
# =========================

# Build arguments for DeepEP source
ARG USE_LOCAL_DEEPEP=false
ARG DEEPEP_REPO=https://github.com/andresnowak/DeepEP.git
ARG DEEPEP_BRANCH=v1.2.1-alps

WORKDIR /home/dpsk_a2a

# Clone from git if USE_LOCAL_DEEPEP=false, otherwise copy local code
RUN if [ "$USE_LOCAL_DEEPEP" = "false" ]; then \
        git clone -b ${DEEPEP_BRANCH} ${DEEPEP_REPO}; \
    else \
        mkdir -p DeepEP; \
    fi

# Copy local code if USE_LOCAL_DEEPEP=true
COPY --chown=root:root . /tmp/deepep-local/
RUN if [ "$USE_LOCAL_DEEPEP" = "true" ]; then \
        cp -r /tmp/deepep-local/* /home/dpsk_a2a/DeepEP/ && \
        rm -rf /tmp/deepep-local; \
    else \
        rm -rf /tmp/deepep-local; \
    fi

ENV LD_LIBRARY_PATH=$NVSHMEM_HOME/lib:$LD_LIBRARY_PATH
ENV PATH=$NVSHMEM_HOME/bin:$PATH


# =========================
# Build DeepEP
# =========================
ENV TORCH_CUDA_ARCH_LIST="9.0"
ENV DISABLE_SM90_FEATURES=0

WORKDIR /home/dpsk_a2a/DeepEP
ENV NVSHMEM_DIR=/home/dpsk_a2a/deepep-nvshmem/install
RUN NVSHMEM_DIR=/home/dpsk_a2a/deepep-nvshmem/install python setup.py develop && \
    NVSHMEM_DIR=/home/dpsk_a2a/deepep-nvshmem/install python setup.py install


# =========================
# Install NVSHMEM Python bindings (nvshmem4py)
# =========================

ENV NVSHMEM_HOME=/home/dpsk_a2a/deepep-nvshmem/install

RUN pip install \
    $NVSHMEM_HOME/lib/python/dist/nvshmem4py_cu12-*-manylinux*.whl


# =========================
# Change the workspace
# =========================
WORKDIR /home/